name       : elfutils
version    : '0.177'
release    : 15
source     :
    - https://sourceware.org/elfutils/ftp/0.177/elfutils-0.177.tar.bz2 : fa489deccbcae7d8c920f60d85906124c1989c591196d90e0fd668e3dc05042e
homepage   : https://fedorahosted.org/elfutils/
license    :
    - GPL-2.0-or-later
    - LPL-3.0-or-later
component  :
    - programming.tools
    - ^libelf : system.base
    - ^libelf-devel : programming.devel
    - ^libelf-32bit : emul32
    - ^libelf-32bit-devel : programming.devel
emul32     : yes
summary    : Utilities and library for manipulating ELF files
description: |
    The elfutils package contains set of utilities and libraries for handling ELF (Executable and Linkable Format) files.
patterns   :
    - ^libelf-devel :
        - /usr/include/elfutils/elf-knowledge.h
        - /usr/include/elfutils/version.h
        - /usr/include/gelf.h
        - /usr/include/libelf.h
        - /usr/include/nlist.h
        - /usr/lib64/libelf*
        - /usr/lib64/pkgconfig
    - ^libelf :
        - /usr/lib64/libelf-*.so
        - /usr/lib64/libelf*.so.1
    - ^libelf-32bit-devel :
        - /usr/lib32/lib*
        - /usr/lib32/pkgconfig
    - ^libelf-32bit :
        - /usr/lib32/libelf-*.so
        - /usr/lib32/libelf.so.1
    - main :
        - /usr/lib64/libasm-*.so
        - /usr/lib64/libdw-*.so
builddeps  :
    - pkgconfig32(zlib)
    - bzip2-devel
rundeps    :
    - devel :
        - libelf-devel
    - ^libelf-devel :
        - libelf
    - ^libelf-32bit :
        - libelf
    - ^libelf-32bit-devel :
        - libelf-devel
setup      : |
    %configure --disable-static \
            --program-prefix=eu-
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -r $installdir/%libdir%/elfutils
    fi
