name       : elfutils
version    : '0.185'
release    : 16
source     :
    - https://sourceware.org/elfutils/ftp/0.185/elfutils-0.185.tar.bz2 : dc8d3e74ab209465e7f568e1b3bb9a5a142f8656e2b57d10049a73da2ae6b5a6
homepage   : https://fedorahosted.org/elfutils/
license    :
    - GPL-2.0-or-later
    - LPL-3.0-or-later
component  :
    - programming.tools
    - ^libelf : system.base
    - ^libelf-devel : programming.devel
    - ^libelf-32bit : emul32
    - ^libelf-32bit-devel : programming.devel
emul32     : yes
summary    : Utilities and library for manipulating ELF files
description: |
    The elfutils package contains set of utilities and libraries for handling ELF (Executable and Linkable Format) files.
builddeps  :
    - pkgconfig32(libcurl)
    - pkgconfig32(zlib)
    - pkgconfig(libarchive)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(sqlite3)
    - bzip2-devel
rundeps    :
    - devel :
        - libelf-devel
    - ^libelf-devel :
        - libelf
    - ^libelf-32bit :
        - libelf
    - ^libelf-32bit-devel :
        - libelf-devel
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        debuginfod="--disable-debuginfod"
    fi
    %configure --disable-static \
            --program-prefix=eu- \
            $debuginfod
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/etc
patterns   :
    - ^libelf-devel :
        - /usr/include/elfutils/elf-knowledge.h
        - /usr/include/elfutils/version.h
        - /usr/include/gelf.h
        - /usr/include/libelf.h
        - /usr/include/nlist.h
        - /usr/lib64/libelf*
        - /usr/lib64/pkgconfig/libelf.pc
    - ^libelf :
        - /usr/lib64/libelf-*.so
        - /usr/lib64/libelf*.so.1
    - ^libelf-32bit-devel :
        - /usr/lib32/lib*
        - /usr/lib32/pkgconfig
    - ^libelf-32bit :
        - /usr/lib32/libelf-*.so
        - /usr/lib32/libelf.so.1
    - main :
        - /usr/lib64/libasm-*.so
        - /usr/lib64/libdebuginfod-*.so
        - /usr/lib64/libdw-*.so
